id: P8AD792AD
initial_creation_type: input
source_metadata:
  title: Shechen Rabjam Rinpoche Series
  language: fr
  description: 'Texts by and about Jigme Chökyi Senge (''jigs med chos kyi seng+ge,
    b. 1966), the seventh Rabjam Rinpoche of Shechen Monastery:'
  volume:
    3259358312024e65aa76312a5029230e:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    69692c863bbf43e38ae969ad42ea4104:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Long Life Prayers
    4c36b22f1489479a8a4ee7df1a7ca7fb:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    8ef0c142c4a740caa33a0eb410c25713:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    1fb81b7b698d4c33b1db935f452cd22f:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Prayers
    b60b24fcc2f547929d9166f318001c51:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    a08a3b7cabea46ef80f693bd5daf7770:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    068de0263796443f88fd81aee105734b:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:35:58.833198'
last_modified_at: '2022-03-01T01:35:58.833201'
